name: Update Parties

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "run"
  run:
    name: 'Update parties-domains.json'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $github.workspace
      - uses: actions/checkout@v2

      - name: Update parties
        id: update-parties
        uses: ./.github/actions/update-parties
        with: 
          source-file: ${{ github.workspace }}/parties-domains.txt
          out-file: ${{ github.workspace }}/parties-domains.json

      # Check if there are any changes to the parties-domains.json file.
      # If there are are then write the date to the parties-domains-last-changed.txt
      # file.
      - name: Check if parties-domains.json is changed
        run: |
          if [ "$(git ls-files --modified | grep -c parties-domains.json)" -ge 1 ]; then date > parties-domains-last-changed.txt; fi
        shell: bash

      # Update parties-domains.json and parties-domains-last-changed.txt files.
      # If there are no changes then no commits are made.
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: |
                parties-domains.json
                parties-domains-last-changed.txt
            commit-msg: Update parties-domains.json
            github-token: ${{ secrets.GITHUB_TOKEN }}
